### ISSUE TITLE
Help Understanding Code and Appropriate Dependancies

### ISSUE THREAD

**Issue by ryanmaxwell96** [snf/keras-fractalnet#6]
Hello,

How many times is the fractalnet built in this code? From the paper, it seems that it should be built numerous times, but is that how this code is working?

Also, what exactly are all of the dependencies for this code as I'm having issues getting it to run with the current versions of keras and tesnorflow I have installed. Also, I've been trying to use Python3 but I'm not sure if it is supposed to be Python3.

**Comment by snf** [comment]
Hi, sorry for the late response. This is unmaintained and, unfortunately, when I did it I didn't write a dependencies file with the versions.
It would be pretty hard making it work as you would also need a CUDA version supported by those Keras+Theano/TF versions
