### ISSUE TITLE
advice for solve the problem #3

### ISSUE THREAD

**Issue by kiritoD** [snf/keras-fractalnet#7]
I run the code with the lastest tensorflow and python3, only modifying a few lines. However, I also enconunter the same problem as mentioned in #3 , I tried solving this problemm following the direction described in #2 , no effect. Afterward, I carefully check all the code and found that when you add the JoinLayer, the parameter 'global_switch' and 'global_path' are set to  fixed values, which means that although this model owns five JoinLayers, all these JoinLayers have different fixed global_switch and global_path respectively. And after these JoinLayers joined to tf Graph, they can only use the fixed values, not flexible values. So the global droppath will take no effect, so will the K,swtich in the function _drop_path(self, inputs). I suggest that the parameter 'global_switch' and 'global_path' can be initialized in the JoinLayer so that they can take effect. @snf

**Comment by snf** [comment]
Hi @kiritoD, thanks for your comment. I haven't looked at it for a few years now and I'm out of date with anything but PyTorch these days.
Please send a PR if you have one and I'll accept and credit you in the README
